services: #TODO Was not able to add not default user
  rabbitmq:
    image: rabbitmq:4.0.4-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ../volumes/rabbitmq/data/:/var/lib/rabbitmq/
      - ../volumes/rabbitmq/log/:/var/log/rabbitmq/
volumes:
  rabbitmq_data: